---
- name: Configure VM and manage Podman containers
  hosts: vm
  become: yes
  vars_prompt:

    - name : passwordToken
       

     
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies for Podman
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - lsb-release
        state: present

    - name: Download Podman GPG key
      command: curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key -o /tmp/Release.key

    - name: Add Podman GPG key
      command: gpg --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg /tmp/Release.key

    - name: Add Podman repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/ /"
        state: present

    - name: Update apt cache after adding Podman repository
      apt:
        update_cache: yes

    - name: Install Podman
      apt:
        name: podman
        state: present

    - name: Start and enable Podman socket
      systemd:
        name: podman.socket
        enabled: yes
        state: started
        
    - name: Login
      command: podman login acrprueba.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p {{ passwordToken }}
    - name: Pull nginx:stable image from ACR
      command: podman pull acrprueba.azurecr.io/nginx:stable
        

    - name: Run Podman container
      command: podman run -d --name contenedornginx -p 80:80 -p 443:443 acrprueba.azurecr.io/nginx:stable
